name: ğŸ’¿ CI Branch

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-branch:
    name: ğŸ­ Build Branch
    runs-on: ubuntu-20.04
    steps:
      - name: ğŸšš Checkout
        uses: actions/checkout@master
      - name: ğŸ›  Setup .NET Core
        uses: actions/setup-dotnet@master
      - name: âš™ Restore
        run: dotnet restore
      - name: ğŸ­ Build
        run: dotnet build --no-restore -c Release /p:ContinuousIntegrationBuild=true
      - name: ğŸ§ª Tests
        run: dotnet test --no-build -c Release --filter FullyQualifiedName\!~Tests.Integration
